CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(40) NOT NULL,
  "password" varchar(20) NOT NULL,
  "age" int NOT NULL,
  "rol_id" int NOT NULL
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(20) NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(100),
  "teacher_id" int NOT NULL,
  "level_course_id" int NOT NULL
);

CREATE TABLE "courses_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(50) NOT NULL,
  "course_video_id" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "category_courses" (
  "category_id" int NOT NULL,
  "category_course_id" int NOT NULL
);

CREATE TABLE "users_courses" (
  "student_id" int NOT NULL,
  "users_course_id" in NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("users_course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "users" ("id");

ALTER TABLE "courses_video" ADD FOREIGN KEY ("course_video_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_course_id") REFERENCES "levels" ("id");

ALTER TABLE "category_courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "category_courses" ADD FOREIGN KEY ("category_course_id") REFERENCES "courses" ("id");


INSERT INTO roles (name) VALUES ('admin'), ('teacher'), ('student');

INSERT INTO users (name, email, password, age, rol_id) VALUES ('Freddy', 'freddza.astorga@gmail.com', 'fredd123', 30, 1), ('Daniela', 'danihaur99@gmail.com', 'Dani1234', 23, 2), ('Fabian', 'fab@gmail.com', 'FAB2301', 17, 3);

INSERT INTO levels (level) VALUES ('Beginner'), ('Intermediate'), ('Advance');

INSERT INTO courses (title, description, teacher_id, level_course_id) VALUES ('Node JS', 'Node is used extensively for server-side programming, making it possible for developers', 2, 1), ('Adobe Illustrator', 'Take your first steps in graphic design.', 2 , 2);

INSERT INTO courses_video (title, url, course_video_id) VALUES ('Node JS', 'https://nodejs.org/en/about', 1), ('Adobe Illustrator Basic', 'www.online.edumac/courses/cursoillustratorbasic', 2);

INSERT INTO categories (name) VALUES ('Development'), ('Image retouching');

INSERT INTO category_courses (category_id, category_course_id) VALUES (1, 1), (2, 2);

INSERT INTO users_courses (student_id, users_course_id) VALUES (1, 1), (1, 2);